=== azerpas/school-8-xml/tp2/ex1/agenda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agenda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="nom"/>
                            <xs:element type="xs:string" name="prenom"/>
                            <xs:element type="xs:int" name="phone"/>
                            <xs:element name="adresse">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="rue"/>
                                        <xs:element type="xs:int" name="numero"/>
                                        <xs:element type="xs:string" name="ville"/>
                                        <xs:element type="xs:int" name="postalcode"/>
                                        <xs:element type="xs:string" name="cedex" minOccurs="0"/>
                                        <xs:element type="xs:string" name="pays"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="type"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== azerpas/school-8-xml/tp2/ex1/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agenda.xsd">
    <contact type="personne">
        <nom>Doe</nom>
        <prenom>John</prenom>
        <phone>0612345678</phone>
        <adresse>
            <rue>Rue de Paris</rue>
            <numero>1</numero>
            <ville>Paris</ville>
            <postalcode>75000</postalcode>
            <pays>France</pays>
        </adresse>
    </contact>
</agenda>
