=== azerpas/school-8-xml/tp5/ex1-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Etudiants",
    "description": "Une liste d'Ã©tudiants",
    "type": "array",
    "minContains": 3,
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "integer"
            },
            "nom": {
                "type": "string"
            },
            "prenom": {
                "type": "string"
            },
            "dateNaissance": {
                "type": "string",
                "pattern": "^([0-2][0-9]|(3)[0-1])(\/)(((0)[0-9])|((1)[0-2]))(\/)\\d{2}$"
            },
            "lieuNaissance": {
                "type": "string"
            },
            "adresse": {
                "type": "object",
                "properties": {
                    "numRue": {
                        "type": "integer"
                    },
                    "nomRue": {
                        "type": "string"
                    },
                    "codePostal": {
                        "type": "integer",
                        "minimum": 10000,
                        "maximum": 99999 
                    },
                    "ville": {
                        "type": "string"
                    }
                },
                "required": [
                    "numRue",
                    "nomRue",
                    "codePostal",
                    "ville"
                ]
            },
            "mail": {
                "type": "string"
            },
            "coursSuivis": {
                "type": "array",
                "items": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "string"
                    }
                ],
                "minContains": 1
            }
        },
        "required": [
            "id",
            "nom",
            "prenom",
            "mail"
        ]
    }
}

=== azerpas/school-8-xml/tp5/ex1.json
[
	{
		"id": 1,
		"nom": "Le Roy",
		"prenom": "Fr√©dric",
		"dateNaissance": "16/12/98",
		"lieuNaissance": "Paris",
		"adresse": {
			"numRue": 1,
			"nomRue": "Boulevard Cappucine",
			"codePostal": 75002,
			"ville": "Paris"
		},
		"mail": "fredlr@gmail.com",
		"coursSuivis": ["francais", "anglais"]
	},
	{
		"id": 2,
		"nom": "Dupont",
		"prenom": "Julie",
		"dateNaissance": "01/03/00",
		"lieuNaissance": "Lille",
		"adresse": {
			"numRue": 10,
			"nomRue": "Rue des Lillas",
			"codePostal": 75010,
			"ville": "Paris"
		},
		"mail": "juliedupont3@gmail.com",
		"coursSuivis": ["francais", "anglais", "mathematiques", "histoire"]
	},
	{
		"id": 3,
		"nom": "Gros",
		"prenom": "Pauline",
		"dateNaissance": "12/10/00",
		"lieuNaissance": "Brest",
		"adresse": {
			"numRue": 10,
			"nomRue": "Rue de l'Arbre",
			"codePostal": 75010,
			"ville": "Paris"
		},
		"mail": "gros-paulinep@gmail.com",
		"coursSuivis": ["francais", "anglais", "mathematiques", "histoire"]
	}
]
